//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Application Menu Stack ver:4.1.20612.0")]
[assembly: AssemblyDescription("Application Menu Stack")]
[assembly: AssemblyProduct("edline")]
[assembly: AssemblyCopyright("Copyright © 2004-2012 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("D37104B5-4108-4799-A7A1-D37F80319D27")]
[assembly: AssemblyVersion("4.1.20612.0")]
[assembly: AssemblyFileVersion("4.1.20612.0")]


