//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("MenuStack ver:4.1.31219.10")]
[assembly: System.Reflection.AssemblyDescription("MenuStack")]
[assembly: System.Reflection.AssemblyCompany("Bricksoft.com")]
[assembly: System.Reflection.AssemblyProduct("MenuStack")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("D37104B5-4108-4799-A7A1-D37F80319D27")]
[assembly: System.Reflection.AssemblyVersion("4.1.31219.10")]
[assembly: System.Reflection.AssemblyFileVersion("4.1.31219.10")]


